#!/bin/bash
# Build script for TL_C5-V4 / WDR5620 Gigabit

if [ -z "$1" ] || [ "$EUID" != 0 ]; then
    echo "Please run 'fakeroot $0 [kmod]' to start build"
    exit 1
fi

# Base config from template
cp -f configs/templates/TL_C5-V4.config .config

# Flash size optimization for 8MB - disable heavy features
cat >> .config << 'EOF'
CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n
CONFIG_FIRMWARE_INCLUDE_XRAY=n
CONFIG_FIRMWARE_INCLUDE_V2RAY=n
CONFIG_FIRMWARE_INCLUDE_TROJAN=n
CONFIG_FIRMWARE_INCLUDE_SSOBFS=n
CONFIG_FIRMWARE_INCLUDE_ADBYBY=n
CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n
CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n
CONFIG_FIRMWARE_INCLUDE_DDNSTO=n
CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n
CONFIG_FIRMWARE_INCLUDE_SQM=n
CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=y
CONFIG_FIRMWARE_INCLUDE_BANDWIDTHD=y
CONFIG_FIRMWARE_INCLUDE_NAIVEPROXY=n
CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n
CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n
EOF

./build_firmware_modify TL_C5-V4 $1
