SRC_NAME = kumasocks
THISDIR = $(shell pwd)

all:

extract_test:

config_test:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/kumasocks /usr/bin/kumasocks
	$(ROMFSINST) -p +x $(THISDIR)/kumasocks.sh /usr/bin/kumasocks.sh
